name: Scrape Web Page and Push

on:
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager

    - name: Open Web Client Directory
      run: |
        ls -la

    - name: Run Scraper
      run: python scraper.py
      
    - name: Commit and Push if Changes Exist
      run: |
        git config --global user.name 'KAWASAKI Teruo'
        git config --global user.email 'kawasaki.teruo@classmethod.jp'
        git add .
        git commit -m 'Update scraped content' || echo "No changes to commit"
        git push
