name: Scrape Web Page and Push

on:
  workflow_dispatch:

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Run Scraper
      run: python scraper.py
      
    - name: Commit and Push if Changes Exist
      run: |
        git config --global user.name 'KAWASAKI Teruo'
        git config --global user.email 'kawasaki.teruo@classmethod.jp'
        git add .
        git commit -m 'Update scraped content' || echo "No changes to commit"
        git push
